### ISSUE TITLE
Creating .scss files inside other folders are not reloading the main .css

### ISSUE THREAD

**Issue by jeanbauer** [FringeLabs/slush-fringe-react#12]
title pretty much self explanatory.

**Comment by vinnylinck** [comment]
I'm on it.

**Comment by vinnylinck** [comment]
Can you provide more details? Just created a project and I have a refresh when changing a .scss file.
Maybe I didn't get what "other folders" mean.

**Comment by vinnylinck** [comment]
Any chance you check if this problem is still happening @jeanbauer ? Thanks.
