### ISSUE TITLE
Update RR to V4

### ISSUE THREAD

**Issue by jeanbauer** [FringeLabs/slush-fringe-react#21]
https://github.com/ReactTraining/react-router/tree/v4 :rocket:

**Comment by vinnylinck** [comment]
Please check #22 

The boilerplate will download basically the last stable stack (react, react-dom, react-router, redux). The generated project package.json file does not force a specific version. just the minimal.

Did you see any issue when generating a project? Is there any specific feature requiring this RR version?

thx

**Comment by jeanbauer** [comment]
Right, I have to test if everything goes well using the v4.
